adjective_1=input("An adjective ")
nationality_1=input("A nationality ")
name_1=input("A proper name ")
noun_1=input("A noun ")
adjective_2=input("An adjective ")
noun_2=input("A noun ")
adjective_3=input("An adjective ")
adjective_4=input("An adjective ")
plural_noun=input("A plural noun ")
noun_3=input("A noun ")
number_1=input("A number ")
shape_1=input("A type shapes ")
food_1=input("A food ")
food_2=input("A food ")
number_2=input("A number ")

print ("Pizza was invented by a " + adjective_1 + " " +  nationality_1 + " chef named " + name_1 + ". To make pizza, you need to take a lump of " + noun_1 + ", and make a thin, round " + adjective_2 + " " +  noun_2 + ". Then you cover it with " + adjective_3 + " sauce, " + adjective_4 + " cheese, and fresh chopped " + plural_noun + ". Next you bake it in a very hot " + noun_3 + ". When it is done, cut it into " + number_1 + " " +  shape_1 + ". Some kids like " + food_1 + " pizza the best, but my favourite is the " + food_2 + " pizza., If I could, I would eat pizza " + number_2 + " times a day!")
